app: exchange
env: staging
namespace: staging
chart:
    repository: https://chart.onechart.dev
    name: onechart
    version: 0.32.0
values:
    image:
        repository: nginxa
    ingress:
        annotations:
            newKey: New Value
    podDisruptionBudgetEnabled: false
    probe:
        enabled: true
    resources:
        limits:
            cpu: 2000m
            memory: 2000Mi
    sealedSecrets:
        newKey: New Value
        newKey-1: New Value
    vars:
        newKey: New Value
    volumes:
        - name: data
          path: /data
          size: 10Gi
          storageClass: ""
